### ISSUE TITLE
es2015 if conversion

### ISSUE THREAD

**Issue by dancinglightning** [rubys/ruby2js#18]
When trying out the each i switched on es2015 for the first time.
So i have a simple if (obviously just about the structure here)
```ruby
      return 1 if true
```
which converts (as i need it) to 
```javascript
    if (true) return 1
```

But with es2015 the ruby line converts to 
```javascript
    true ? return 1 : null
```

Which in turn does not seem to be valid js (chrome 63, latest), so i get a `SyntaxError: Unexpected token return`

I can't really even find where this happens. And i wonder why? Is a ternary operator faster for a simple if? I usually only use it for assignments.

**Comment by rubys** [comment]
Background: there is no difference in the AST generated by if statements and ternary operators.  Ruby2js keeps track of whether it is running in a statement context or an expression context so that it knows which of the two forms to generate.  There was a bug (now fixed) in the code that produces es2015 arrow operators instead of classic anonymous function syntax, causing the wrong form to be produced.

Good catch!

**Comment by dancinglightning** [comment]
ok cool. got that part
