### ISSUE TITLE
unknown AST type irange 

### ISSUE THREAD

**Issue by kevjett** [rubys/ruby2js#24]
I've been having an issue converting ranges. It continues to tell me that it is an unknown AST type.  So I tried to take one of the spec tests and run it in the demo to see if it was my code and it's still failing. Does anyone know if this is a bug or I'm doing something wrong.

I tried this from the spec in the demo and it gave the same error as my code (unknown AST type irange ):

`(1..10).each {|i| p i}`

**Comment by rubys** [comment]
There is no complete equivalent to Ruby ranges in JavaScript, but specific idioms (including the one you've included above) is supported by the `functions` filter.

Try the following:

```ruby
require 'ruby2js/filter/functions'

puts Ruby2JS.convert('(1..10).each {|i| p i}')
```

**Comment by kevjett** [comment]
It looks like it passes in the unit test but it won't work on the demo page. Do you know why `(1..10).each {|i| p i}` doesn't work there?

**Comment by rubys** [comment]
Try adding `/functions/` to the URL.  Example: http://intertwingly.net/projects/ruby2js.cgi/functions/

**Comment by kevjett** [comment]
I'm actually running as a standalone server with `ruby ruby2js.rb --port=8080` so the URL I'm using is http://localhost:8080/functions/ this still didn't work. All other conversions work correctly. Just not when it tries a range. For example, I just converted the entire demo/ruby2js.rb file and it worked great.

**Comment by rubys** [comment]
Try adding `require 'ruby2js/filter/functions'` to ruby2js.rb.

Background on this: mapping `.each` to a `for` statement is very helpful, up until the point where you try to call a method like [`JQuery.each`](http://api.jquery.com/jquery.each/).  That's why you have to opt in on this behavior.  It is also possible to opt out of this behavior on an individual call by adding an `!` to the method call, thus: `jQuery.each!`.

**Comment by rubydesign** [comment]
Wouldn't it be an idea to have functions by default?
there is always the ! trick.
Not having it default seems to confuse more than serve.

**Comment by kevjett** [comment]
I added `require 'ruby2js/filter/functions'` to the top of the demo page and that worked. I don't really understand why it didn't do that by default. Thanks for the help though. Just FYI, I did find a conversion it didn't do but seems it's just not supported. It's the <=> sign used for sorting. Ex. `myarray.sort!{|a,b| a.age <=> b.age }`

**Comment by rubys** [comment]
I would not be opposed to documenting filter/functions better; but its use can take correct code and produce incorrect code.  That's why I feel that it should be opt-in.  And opting in is as simple as a single require statement.

As to the `<=>` operator, something like the following could be produced:

```javascript
myarray.sort((a, b) => {if (a.age < b.age) {return -1} else {return (a.age > b.age ? 1 : 0)}})
```

If this is of interest, open a separate issue.

**Comment by kevjett** [comment]
Ok, I'll open another issue just to help keep track of enhancements. 

I just ran into another erange error with this code, does it support ranges in case statements?

```
def mymethod
    case bp_range
    when -999...0
      10
    when 1...2
      100
    when 2...5
      120
    when 6...10
      150
    when 11...40
      129
    else
      150
    end
  end
```

**Comment by rubys** [comment]
Please open a separate issue on erange and case statements.  There is no direct equivalent in JavaScript, but there are a few alternatives: https://stackoverflow.com/questions/5619832/switch-on-ranges-of-integers-in-javascript

**Comment by kevjett** [comment]
Thanks. I will. I was just looking at that discussion as well. :)

**Comment by cerdiogenes** [comment]
I'm able to run `puts Ruby2JS.convert('(1..10).each {|i| p i}')` in the console, but not in the asset pipeline. Can you help?

**Comment by cerdiogenes** [comment]
I needed to also require `require 'ruby2js/filter/rubyjs'` :thinking:

**Comment by rubys** [comment]
@cerdiogenes try: `require 'ruby2js/filter/functions'` instead.  You will get a different mapping, one that doesn't depend on http://rubyjs.org/.

**Comment by cerdiogenes** [comment]
I already `require 'ruby2js/filter/functions'`. It's only worked after also `require 'ruby2js/filter/rubyjs'`.

**Comment by rubys** [comment]
Odd, filter functions has supported range.each since January: https://github.com/rubys/ruby2js/commit/0798d90d59670ff3600a3255e642455ed5508750; are you by any chance using ruby2js version 2.1.24 or earlier?

Compare the output produced by the following two pages: http://intertwingly.net/projects/ruby2js.cgi/rubyjs/ and http://intertwingly.net/projects/ruby2js.cgi/functions/

**Comment by cerdiogenes** [comment]
I'm using from github master. The strange is that in the console it's work, but not in the asset pipeline.
